name: Deploy Frontend to Tencent Cloud

on:
  push:
    branches: [ main ]
    paths:
      - 'front/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # 禁用严格主机密钥检查
        echo -e "Host ${{ secrets.SSH_HOST }}\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" >> ~/.ssh/config
        
    - name: Validate files
      run: |
        echo "前端文件结构:"
        ls -la front/
        
    - name: Create deployment package
      run: |
        mkdir -p front-dist
        cp -r front/* front-dist/
        echo "Deployment package created at $(date)" > front-dist/deployment-info.txt
        
    - name: Deploy files via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "front-dist/*"
        target: "/var/www/front"
        strip_components: 0
        
    - name: Configure Nginx
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # 创建nginx配置
          sudo bash -c 'cat > /etc/nginx/sites-available/front.conf <<EOF
          server {
              listen 80;
              server_name localhost;
              
              root /var/www/front;
              index index.html;
              
              location / {
                  try_files \$uri \$uri/ /index.html;
              }
              
              location /api {
                  proxy_pass http://localhost:8080;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
              }
              
              # 静态资源缓存
              location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                  expires 1y;
                  add_header Cache-Control "public";
              }
          }
          EOF'
          
          # 启用配置
          sudo ln -sf /etc/nginx/sites-available/front.conf /etc/nginx/sites-enabled/
          sudo nginx -t && sudo systemctl restart nginx
          
    - name: Verify deployment
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "部署目录内容:"
          ls -la /var/www/front
          echo "Nginx服务状态:"
          systemctl status nginx --no-pager
          echo "测试访问:"
          curl -I http://localhost